author: ZephireNZ
database: false
main: nz.co.noirland.noirstore.NoirStore
name: NoirStore
startup: postworld
version: ${version}
depend: [Vault]
commands:
  noirstore:
    description: Manages the NoirStore plugin
    usage: /<command> [reload/override]
    default: op