author: ZephireNZ
database: false
main: nz.co.noirland.noirstore.NoirStore
name: NoirStore
startup: postworld
version: ${version}
depend: [Vault, ZephCore]
api-version: 1.13
commands:
  noirstore:
    description: Manages the NoirStore plugin
    usage: /<command> [reload/override]
    default: op